create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint not null, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint not null, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint not null, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint not null, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint not null, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint not null, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint not null, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint not null, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint not null, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
create table address (id bigint generated by default as identity, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint generated by default as identity, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint generated by default as identity, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
create table address (id bigint generated by default as identity, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint generated by default as identity, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint generated by default as identity, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
create sequence address_sequence start with 1 increment by 50
create sequence author_sequence start with 1 increment by 50
create sequence book_sequence start with 1 increment by 50
create sequence publisher_sequence start with 1 increment by 50
create table address (id bigint not null, address varchar(255), city varchar(255), state varchar(255), zip bigint, primary key (id))
create table author (id bigint not null, first_name varchar(255), last_name varchar(255), primary key (id))
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id))
create table book (id bigint not null, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id))
create table publisher (id bigint not null, name varchar(255), address_id bigint, primary key (id))
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher
alter table publisher add constraint FKsw6h0k6uwmywa01est3ydvj5m foreign key (address_id) references address
